map: {}
game:
  playerJoin: '&a\u27A3 &6%player% &ahas joined. &7[&6%players%/%maxPlayers%&7]'
  playerQuit: '&c\u2718 &6%player% &ahas left. &7[&6%players%/%maxPlayers%&7]'
  playerWinTitle: '&6&l%player% &aHas Won!'
  gameStartingMessage: '&aStarting in &6%int% &aseconds!'
  lastGameStartingMessage: '&aStarting in &61 &asecond!'
  gameStartingTitle: '&aStarting in &6%int% &a...'
  gameStartTitle: '&a&lSplegg!'
  resetCountdown: '&aReseting countdown, not enough players'
  mapSelected: '&aThe map &6%string% &a has been selected!'
  playerDeath: '&6%player% &adied'
  vote: '&6%player% &a voted for &6%string%   &7|   &6%int% &a votes'
  voteError: '&a/vote #'
  alreadyVoted: '&aYou have already voted!'
  voteEnded: '&aVoting has ended!'
  voteMenuHeader: '&7----------------------------'
  voteMenuInstructions: '&aTo vote click on a map or use /vote #'
  voteMenuMap: '&7[&6%mapNumber%&7] &6%mapName%   &7|   &6%mapVotes% &avotes'
  voteMenuHover: '&aClick to vote for &6%string%'
  voteMenuFooter: '&7----------------------------'
  inGameScoreboardHeader: '&7&lSplegg [%minutesLeft%:%secondsLeft%]'
  inGameScoreboardPlayers: '&a&lPlayers: &6&l%allivePlayers%'
  inGameScoreboardEliminated: '&a&lEliminated: &6&l%eliminated%'
  inGameScoreboardSpectators: '&a&lSpectators: &6&l%spectators%'
  inGameScoreboardPlayersIdentifier: 'Players'
  inGameScoreboardEliminatedIdentifier: 'Eliminated'
  inGameScoreboardSpectatorsIdentifier: 'Spectators'
  preGameScoreboardHeader: '&7&lSplegg'
  preGameScoreboardWins: '&a&lWins: '
  preGameScoreboardGamesPlayed: '&a&lGames Played'
  preGameScoreboardEggsShot: '&a&lEggs Shot'
  preGameScoreboardBlocksDestroyed: '&a&lBlocks Destroyed'
  preGameScoreboardDeaths: '&a&lDeaths'
  preGameScoreboardPointsAquired: '&a&lTotal Points'
debug: true
